In [ ]:
import numpy as np
x = [-0.1, 0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7]
f = [0.5487, 0.5487, 0.6137, 0.7317, 0.8727, 0.9820, 0.9780, 0.7712, 0.3153, -0.3138]
h = 0.2

u = np.zeros(10)
for i in range(1,10):
    u[i] = (f[i] - f[i-1])/h
    
p = np.zeros(10)
p[1] = -h/(4*h)
for i in range(3,10):
    p[i-1] = -h/(4*h + h*p[i-2])
    
q = np.zeros(10)
q[1] = 3*(u[2]-u[1])/(4*h)
for i in range(3,10):
    q[i-1] = (3*u[i] - 3*u[i-1] - h*q[i-2])/(4*h + h*q[i-2])
    
c = np.zeros(10)
for i in reversed(range(2,10)):
    c[-(i-1)] = p[-(i-1)] + q[-(i-1)]
    
b = np.zeros(10)
for i in range(1,10):
    b[i] = u[i] + (2*c[i]*h + h*c[i-1])/3
    
    
d = np.zeros(10)
for i in range(1,10):
    d[i] = (c[i] - c[i-1])/(3*h)

a = np.zeros(10)
for i in range(1,10):
    a[i] = f[i]
    
def interp0late(k):
    S = np.zeros(10)
    v = 0
    w = 0
    for i in range(1,10):
        S[i] = a[i] + b[i]*(k-x[i]) + c[i]*(k-x[i])**2 + d[i]*(k-x[i])**3
    while v<10:
        if (x[v] <= k) & (k < x[v+1]) :
            w = S[v]
            v=11
        else:
            v+=1
    return w

In [83]:
import pandas as ps
mas = np.zeros((8,10))
mas[0,:] = u[:]
mas[1,:] = p[:]
mas[2,:] = q[:]
mas[3,:] = a[:]
mas[4,:] = b[:]
mas[5,:] = c[:]
mas[6,:] = d[:]
tab = ps.DataFrame(data=mas, index=np.arange(0,8), columns=np.arange(0,10))
tab.index = ['u','p','q','a','b','c','d','comppa']

In [108]:
g = np.zeros(10)
for k in range(2,10):
    g[k-1] = b[k] - 2*c[k]*h + 3*d[k]*h**2
mas[7,:] = g[:]
tab

,0,1,2,3,4,5,6,7,8,9
u,0.0,0.000000,0.325000,0.590000,0.705000,0.546500,-0.020000,-1.034000,-2.279500,-3.145500
p,0.0,-0.250000,-0.266667,-0.267857,-0.267943,-0.267949,-0.267949,-0.267949,-0.267949,0.000000
q,0.0,1.218750,0.528144,0.264315,-0.619517,-2.330431,-7.714308,2.952957,-2.292975,0.000000
a,0.0,0.548700,0.613700,0.731700,0.872700,0.982000,0.978000,0.771200,0.315300,-0.313800
b,0.0,0.000000,0.359864,0.606960,0.586436,0.140885,-1.257526,-1.208149,-2.441956,-3.316228
c,0.0,0.000000,0.261477,-0.003542,-0.887459,-2.598380,-7.982257,2.685008,-2.560924,0.000000
d,0.0,0.000000,0.435795,-0.441699,-1.473195,-2.851534,-8.973129,17.778775,-8.743220,4.268207
comppa,0.0,0.307568,0.555373,0.764636,0.838053,0.858601,-0.148700,-2.466773,-2.804043,0.000000

In [106]:
interp0late(1)

0.9672532067518822